### ISSUE TITLE
Date display in the energy data display incomplete

### ISSUE THREAD

**Issue by EEG-VIERE** [eegfaktura/eegfaktura-web-docker#5]

**Comment by EEG-VIERE** [comment]
If you move the cursor over the bars of the energy diagram, a pop-up window appears in which the data is displayed. Where the date should be, only a number (day of the month) is displayed. It would be ideal if e.g. 16.10.23 would be displayed here.



![Image](https://github.com/eegfaktura/eegfaktura-web/assets/121015566/e9388e71-aff5-4e06-ac17-55b13a9d13fb)

**Comment by LucaGeissler** [comment]
Replace the Number which indicates the current day with a more precise information for the user, "11.Dezember.2023"

**Comment by andihame** [comment]
better use "11.12.2023"
